packages:
  - packages/*
  - plugin
  - scratchpad
  - vscode
  - website
allowBuilds:
  "@vscode/vsce-sign": false
  keytar: false
autoInstallPeers: true
configDependencies:
  "@effected/pnpm-plugin-effect": 0.13.6
  "@savvy-web/pnpm-plugin-silk": 0.47.0
