packages:
  - packages/*
  - plugins/*
autoInstallPeers: true
configDependencies:
  "@effected/pnpm-plugin-effect": 0.8.12+sha512-dBghPn8FT93fnlByKG/dL9QHJ3TN6cwB6I6QhBsy+8aJg4VZJT0ygwjsWRUoC6hJ1Ajq5eQrIHIBq07lJvtsFQ==
  "@savvy-web/pnpm-plugin-silk": 0.38.0+sha512-81i8SnZZMriVwO8bKYrsTkinKd5JOgzXFUxHn7TpaPd91pO1rwQh2Mnnvujn0De3ZrBFG6EGCgWdTKAdzrdO2w==
linkWorkspacePackages: deep
minimumReleaseAgeExclude:
  - "@rolldown/binding-openharmony-arm64@1.2.8"
  - "@turbo/darwin-arm64@2.10.13"
  - "@turbo/linux-64@2.10.13"
  - "@turbo/windows-arm64@2.10.13"
verifyDepsBeforeRun: false
