packages:
  - packages/*
  - plugins/*
  - scratchpad
  - vscode
allowBuilds:
  "@vscode/vsce-sign": false
  keytar: false
autoInstallPeers: true
configDependencies:
  "@effected/pnpm-plugin-effect": 0.11.0+sha512-BTM4CshUSQvYUN6w6uKexdeNrCZK3tat7yB5aENbVDte5FlMzyfr5qFdgbMr/o2WeZrvZyZ2+sTU/+YvZ3a2qA==
  "@savvy-web/pnpm-plugin-silk": 0.42.0+sha512-2KQ/+3C+ciQ+1I/Vpfr+875Guta0YtCPNodeZkB2kegaraItEGwaYxIx8OocWglaoCbYC44acTJhQwxIRWhNdw==
