# Generated by pluginfinity. Do not edit.
_PF_TOOLS='Read=view
Bash=bash
Edit=edit
MultiEdit=edit
Write=create
Agent=task
Task=task
Grep=grep
Glob=glob
WebFetch=web_fetch
WebSearch=web_search
Skill=skill'
_PF_TOOLS_PLUGIN='okfit'
_PF_TOOLS_MCP='{server}-{tool}'
_PF_TOOLS_SERVERS='mcp'
_PF_TOOLS_UNLISTED=unresolved
_PF_HAS_SKILLS='docs-badges docs-detect-shape docs-humanize docs-render docs-templates okf-authoring okf-config okf-context okf-finalize okf-spec'
_PF_HAS_AGENTS='okf-docs okf-publisher'
_PF_HAS_MONITORS=''
_PF_HAS_SERVERS='mcp'
