# Generated by pluginfinity. Do not edit.
_PF_TOOLS=''
_PF_TOOLS_PLUGIN='okfit'
_PF_TOOLS_MCP='mcp__plugin_{plugin}_{server}__{tool}'
_PF_TOOLS_SERVERS='mcp'
_PF_TOOLS_UNLISTED=keep
_PF_HAS_SKILLS='docs-badges docs-detect-shape docs-humanize docs-render docs-templates okf-authoring okf-config okf-context okf-finalize okf-spec'
_PF_HAS_AGENTS='okf-docs okf-publisher'
_PF_HAS_MONITORS=''
_PF_HAS_SERVERS='mcp'
